### ISSUE TITLE
Unable to Process --first-message Response

### ISSUE THREAD

**Issue by pulltab** [machinezone/tcpkali#1]
I am attempting to use tcpkali to benchmark a system which responds to the first-message with a JSON encoded payload of {success: true} or {success: false, reason: string()}. The former ({success: true}) also serves as our latency marker.

This prevents us from using tcpkali as I see the following error message shortly after tcpkali ramps up connections:

```bash
More messages received than sent. Choose a different --latency-marker.
```

In this case, I would like to be able to expect a certain result from --first-message as, in my case, this pertains to whether or not a connection initialized successfully.

**Comment by vlm** [comment]
1. Is it WebSocket or plain TCP stream?

2. Would '--skip-latency-markers <N>' work?

**Comment by pulltab** [comment]
1) Websocket

2) If --skip-latency-markers accepted a second argument which allowed me to specify the number of markers to skip.  In this case, I want to measure latency.

**Comment by vlm** [comment]
Fixed, enjoy `--latency-marker-skip`!
