### ISSUE TITLE
Doesnt build on Ubuntu

### ISSUE THREAD

**Issue by varunvedanth** [machinezone/tcpkali#19]
make[2]: Entering directory `/home/*****/Downloads/tcpkali-0.8/src'
gcc -DHAVE_CONFIG_H -I. -I..  -I../deps/libev -I../deps/libcows -I../deps/libstatsd/src -I../deps/HdrHistogram -I../deps/boyer-moore-horspool  -std=gnu99 -W -Wall -Wno-strict-aliasing -fno-strict-aliasing -g -O2 -pthread -MT tcpkali-tcpkali_terminfo.o -MD -MP -MF .deps/tcpkali-tcpkali_terminfo.Tpo -c -o tcpkali-tcpkali_terminfo.o `test -f 'tcpkali_terminfo.c' || echo './'`tcpkali_terminfo.c
tcpkali_terminfo.c:149:6: error: conflicting types for ‘tcpkali_init_terminal’
 void tcpkali_init_terminal(void) { return; }
      ^
In file included from tcpkali_terminfo.c:43:0:
tcpkali_terminfo.h:34:5: note: previous declaration of ‘tcpkali_init_terminal’ was here
 int tcpkali_init_terminal(void);
     ^
make[2]: *** [tcpkali-tcpkali_terminfo.o] Error 1
make[2]: Leaving directory `/home/*****/Downloads/tcpkali-0.8/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/*****/Downloads/tcpkali-0.8'
make: *** [all] Error 2

**Comment by vlm** [comment]
1. That one was fixed in the latest code (not in the release).
2. Make sure you download the libncurses-devel (or whatever libncurses is called on Ubuntu), then do `./configure` again. That'll remove this error from your particular version of tcpkali.
