### ISSUE TITLE
Can't open more than 1000 connections on mac os x

### ISSUE THREAD

**Issue by sitnikovme** [machinezone/tcpkali#2]
Mac OS X 10.10.3 (14D136)

18:06 $ ~/bin/tcpkali -c 1100 -T 60 127.0.0.1:3000
Destination: [127.0.0.1]:3000
WARNING: 1100 connections might not be opened at a rate 100 within test duration 60.
Decrease --connections=1100, or increase --duration=60 or --connect-rate=100.
(libev) select: Invalid argument============>-----| 999 of 1100 (999)
Abort trap: 6

**Comment by vlm** [comment]
1. Run as: `LIBEV_FLAGS=8 ~/bin/tcpkali -c 1100 -T 60 127.0.0.1:3000`
2. The patch is coming.

**Comment by vlm** [comment]
Fixed, as part of https://github.com/machinezone/tcpkali/commit/0a5d9a57268c24b37d9bab9bc7ef5ffda705f15b, will make into the next release.

Meanwhile, use the above `LIBEV_FLAGS=8` hack on your existing `tcpkali` build, and be sure to increase the number of available file descriptors through `ulimit -n`.
