### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [machinezone/tcpkali#20]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/machinezone/tcpkali/blob/53b7f55c54095cf47a1a16676fbe6eafd010af4a/configure.ac#L32 "Configuration checks")?

**Comment by vlm** [comment]
Fixed, thank you!

**Comment by elfring** [comment]
I find that [this approach](https://github.com/machinezone/tcpkali/commit/496e2bda83863fcd1de2ad3e118d81904b82e8d6#diff-67e997bcfdac55191033d57a16d1408aR17 "Update candidate") can be improved a bit more.
