### ISSUE TITLE
Check return codes everywhere

### ISSUE THREAD

**Issue by elfring** [machinezone/tcpkali#21]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [read_in_file](https://github.com/machinezone/tcpkali/blob/7a94b6d53175522c1250f9ad87468adc1de1bc89/src/tcpkali_data.c#L167)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [engine_start](https://github.com/machinezone/tcpkali/blob/7a94b6d53175522c1250f9ad87468adc1de1bc89/src/tcpkali_engine.c#L307)

**Comment by vlm** [comment]
Fixed, thanks for catching!

**Comment by elfring** [comment]
I do not like [the use of the assert macro](https://github.com/machinezone/tcpkali/commit/ab04ee4ac5940e782ef906af34ae66298deacc20#diff-f330e2e92e8e4e8969efe65ef1863b9dR360 "More error detection") because unexpected results will still be ignored if the preprocessor symbol "`NDEBUG`" will be defined. I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by vlm** [comment]
There's a point of diminishing return. What if a user adds system("rm -rf /") into main() before compiling the program? What if the user enables NDEBUG by modifying the ./configure script against the recommendations? There's an endless list of these things for any given C program.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?
