### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [machinezone/tcpkali#22]
I guess that a different program design will be needed for your function "[signal_handler](https://github.com/machinezone/tcpkali/blob/1e397a6fb34465a884350ec372c0d4ee7f7b7624/src/tcpkali_signals.c#L36 "Check signal handling implementation.")".
* The variable "flagvar" should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.").
* The function "[fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by vlm** [comment]
Fixed, thank you!

**Comment by elfring** [comment]
I find that there are still [a few update candidates left over](https://github.com/machinezone/tcpkali/commit/d2c457545a9cac66d8128ff4e1bc14de38dd6ca9#diff-85cdcf6d5f3a8e8a398e70458d3f0b93R37 "Check signal handling implementation once more.").
