### ISSUE TITLE
Support micro / nano second latencies

### ISSUE THREAD

**Issue by nkrode** [machinezone/tcpkali#25]
I assume latencies are reported in ms? However if the response times are below milli seconds range, the latency report shows 0s and nan, example below.

Latency at percentiles: 0.0/0.0/0.0 (95/99/99.5%)
Mean and max latencies: nan/0.0 (mean/max)

**Comment by vlm** [comment]
The latencies are reported in milliseconds. However, the internal resolution is 1/10 of a millisecond. So if you see nan/0.0 it means that no latencies were recorded.
