### ISSUE TITLE
Latency Value is too Large, can't record

### ISSUE THREAD

**Issue by nkrode** [machinezone/tcpkali#27]
Seeing errors like below while running tests:

Latency value 223.976 is too large, can't record.
Latency value 224.032 is too large, can't record.
Latency value 219.1 is too large, can't record.
Latency value 219.407 is too large, can't record.
Latency value 220.719 is too large, can't record.
Latency value 218.847 is too large, can't record.
Latency value 223.449 is too large, can't record.
Latency value 217.907 is too large, can't record.
Latency value 209.543 is too large, can't record.
Latency value 124.174 is too large, can't record.
Latency value 197.907 is too large, can't record.
Latency value 218.193 is too large, can't record.
Latency value 234.989 is too large, can't record.
Latency value 209.13 is too large, can't record.
Latency value 204.588 is too large, can't record.
Latency value 216.269 is too large, can't record.

**Comment by vlm** [comment]
If the other system does not respond within a reasonable time (100 seconds) we decide that it won't respond and thus we don't store latency values. This is a limitation of the underlying data structure that we use to store latencies (HdrHistogram). It needs to be initialized with some maximum value.

If you're experiencing these problems it might mean that either the remote system doesn't respond in time, or your `--latency-marker` specifies a pattern that's not always present in the server responses. Please check this out.
