### ISSUE TITLE
Send query parameters on connection

### ISSUE THREAD

**Issue by arichiardi** [machinezone/tcpkali#30]
Dear maintainer,

in order to benchmark the behavior of my server-side websocket implementation, I need to have some payload sent as query query parameter (`?client-id`), see Wireshark dump below:

```
GET /chsk?client-id=bd5ee0f2-dc22-47b5-98ab-618711f34b45 HTTP/1.1
Host: localhost:3000
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://localhost:3000
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2824.0 Safari/537.36
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,fr-FR;q=0.6,fr;q=0.4
Cookie: ...
Sec-WebSocket-Key: Nl49IiqBKuyC/x5FVHrqwA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

At the moment `tcpkali` sends a message, but I have not found a way to send it as query the moment the handshake is established. I would be willing to contribute the feature but my C is a bit rusty (I haven't been doing it for 10 years or so). I would for sure need some guidance.

First things first, would you be open to such a feature?

Thanks for your work by the way!
Andrea.

**Comment by arichiardi** [comment]
I had a look at the code and given that the [`path` variable is passed directly here](https://github.com/machinezone/tcpkali/blob/master/src/tcpkali_transport.c#L62)

I can do:

`tcpkali --ws --message "neyi" localhost:3000/chsk?client-id=hey-ma-look!`

And have a wonderful injecting wokaround :smile:

**Comment by vlm** [comment]
Yup :)
