### ISSUE TITLE
Use of \{ws.text <file>}

### ISSUE THREAD

**Issue by arichiardi** [machinezone/tcpkali#32]
Hello again :smile: 

I am trying to use `\{ws.text <mypayload>}` but I cannot quite get the desired result.
Can I ask you what is the format I should use in the file?

Should it be a newline-separated series of strings (In my case JSON)?

A big thanks,
Andrea.

**Comment by vlm** [comment]
What result do you want to get?

**Comment by arichiardi** [comment]
I was thinking of sending different payload , line by line. I saw that one line works fine and I was wondering what happens if I put two, three...

On September 16, 2016 6:22:38 PM PDT, Lev Walkin <notifications@github.com> wrote:
>What result do you want to get?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/machinezone/tcpkali/issues/32#issuecomment-247740901

-ar

**Comment by vlm** [comment]
If you need to send different payloads, what you could do, in the order of semantic transparency:

1. Use multiple specifications of `-f `_filename_. As in `tcpkali --ws -f foo.json -f bar.json -f baz.json`.
2. Use multiple specifications of `-m \{ws.text <payload>}`: `tcpkali --ws -m '\{ws.text <foo.json>}' -m '\{ws.text <bar.json>}' -m '\{ws.text <baz.json>}'`
3. Use multiple frames in a single `-m` spec: `tcpkali --ws -m '\{ws.text <foo.json>}\{ws.text <bar.json>}\{ws.text <baz.json>}'`

Some of it should help. Ejoy!

**Comment by arichiardi** [comment]
Oh cool thank you, I'll try it out.

On September 16, 2016 9:08:58 PM PDT, Lev Walkin <notifications@github.com> wrote:
>If you need to send different payloads, what you could do, in the order
>of semantic transparency:
>
>1. Use multiple specifications of `-f `_filename_. As in `tcpkali --ws
>-f foo.json -f bar.json -f baz.json`.
>2. Use multiple specifications of `-m \{ws.text <payload>}`: `tcpkali
>--ws -m '\{ws.text <foo.json>}' -m '\{ws.text <bar.json>}' -m
>'\{ws.text <baz.json>}'`
>3. Use multiple frames in a single `-m` spec: `tcpkali --ws -m
>'\{ws.text <foo.json>}\{ws.text <bar.json>}\{ws.text <baz.json>}'`
>
>Some of it should help. Ejoy!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/machinezone/tcpkali/issues/32#issuecomment-247747773

-ar
