### ISSUE TITLE
connection.uid corrupts message

### ISSUE THREAD

**Issue by jkarneges** [machinezone/tcpkali#34]
For example, if I run:

```
tcpkali -em 'GET /image-\{connection.uid%10}.jpg\r\n\r\n' localhost:8000
```

Then, the server receives the message but with 6 seemingly-bogus bytes prepended: `81 a3 00 00 00 00`, and the last 6 bytes of the message missing (`pg\r\n\r\n` not sent).

If I don't use a connection.uid expression in the message then this problem doesn't happen.

**Comment by vlm** [comment]
Fixed, thank you!
