### ISSUE TITLE
HdrHistogram output

### ISSUE THREAD

**Issue by leozilla** [machinezone/tcpkali#37]
Even if tcpkali supports statsd output it would be nice to also get the output of the HdrHistogram like its done in wrk2.
See: https://github.com/giltene/wrk2#basic-usage

I prefer this output because it can very simply be visualized on http://hdrhistogram.github.io/HdrHistogram/plotFiles.html or further manipulated via gnuplot etc.

**Comment by vlm** [comment]
Use `-vvv` to display the histograms.
