### ISSUE TITLE
Add time unit to latency percentile output

### ISSUE THREAD

**Issue by leozilla** [machinezone/tcpkali#38]
Running with `--latency-marker` gives the following output:

$ tcpkali -c 50 -r 1000 -T 60s --websocket --latency-marker "pong" --message "ping" localhost:8080
WARNING: Dumb terminal, expect unglorified output.
Destination: [127.0.0.1]:8080
Interface lo address [127.0.0.1]:0
Using interface lo to connect to [127.0.0.1]:8080
Ramped up to 50 connections.
Total data sent:     28.6 MiB (30009173 bytes)
Total data received: 17.2 MiB (18005609 bytes)
Bandwidth per channel: 0.128⇅ Mbps (16.0 kBps)
Aggregate bandwidth: 2.401↓, 4.001↑ Mbps
Packet rate estimate: 48796.8↓, 44670.8↑ (1↓, 1↑ TCP MSS/op)
Message latency at percentiles: **0.0/0.2/0.4** (95/99/99.5%)
Test duration: 60.002 s.

The latency at percentiles section could be improved by showing the time unit of those values.
For example I am not sure if the 99.5% is 0.4ms or if its some other time unit.

**Comment by vlm** [comment]
Fixed, thank you!
