### ISSUE TITLE
Long running server

### ISSUE THREAD

**Issue by davidn** [machinezone/tcpkali#41]
When testing lots of machines, it may be desirable to use a tcpkali server purely as an endpoint for multiple tcpkali clients, with the test driven on the client side. In this situation, we may want the server to run for unlimited connections and indefinite time.

The interface for this could be "-1" to the -T option indicating unlimited time.

**Comment by vlm** [comment]
I use `-T1y` for that (1 year), but your suggestion is semantically cleaner ;)
