### ISSUE TITLE
Wrong message rate value when {re } is present

### ISSUE THREAD

**Issue by timofey-barmin** [machinezone/tcpkali#49]
Trying to send 100K messages per second but message counter shows only 1K-ish number. Actual rate is 100K though (could be confirmed by bitrate and by message rate on receiving side):

Sender (message rate is wrong):
```
tcpkali 127.0.0.1:12345 --ws  -T 30m -c1 -m '\{re [0-9]}\{message.marker}' -r100000
🕛  Traffic 0.000↓, 29.435↑ Mbps (0↓ 1↑ 0⇡; 1) (0↓ 786↑ mps) (m=? ms⁹⁵ᵖ)
```
Receiver (message rate is correct):
```
tcpkali -l 12345 --ws -T 1d --message-marker
🕛  Traffic 29.857↓, 0.000↑ Mbps (1↓ 0↑ 0⇡; 27) (100868↓ 0↑ mps) (m=16.9 ms⁹⁵ᵖ)
```

If {re ...} expression is removed from the message the bug disappears.

**Comment by vlm** [comment]
Fixed, try please?

**Comment by timofey-barmin** [comment]
no, still failing
I've updated PR with fix, take a look please https://github.com/machinezone/tcpkali/pull/51

**Comment by timofey-barmin** [comment]
PR merged
