### ISSUE TITLE
Cannot open multiple websockets

### ISSUE THREAD

**Issue by marcoeg** [machinezone/tcpkali#6]
When trying to open more than one websocket endpoint, only the first one is used.

$ tcpkali --websocket  --message "ping" --message-rate=20 --latency-marker="\n" --verbose=3  devel.cometa.io:8000/v1/websockets/1/ca77d88d78ff01fbe816490e8fb436c61d9f3fb3  devel.cometa.io:8000/v1/websockets/2/1cc75625d88fce1777b6b5cf8dfd5344a3a2d0df

I get the double destination but messages are only sent to the first one.

Destination: [54.241.247.101]:8000
Destination: [54.241.247.101]:8000

**Comment by vlm** [comment]
Use `-c 2` flags. By default, only one connection is opened, irrespectively of the number of destinations.
